name: GifService-Build-Wokflow

on:
    push:
      branches:
        - master

jobs:
    gifservice-build:
        runs-on: ubuntu-latest
        #runs-on: self-hosted # Self-hosted runner

        steps:

            - name: Git clone gifservice repository
              uses: actions/checkout@v1
            
            - name: List current folder before Build
              run: ls -la

            - name: Install Java
              uses: actions/setup-java@v3
              with:
                distribution: temurin
                java-version: 11
            
            - name: Check Java version
              run: java -version
            
            - name: Init gradle wrapper
              run: gradle wrapper

            - name: Check Gradle version
              run: ./gradlew --version

            - name: Build with Gradle wrapper
              run: ./gradlew build

            #- name: Install tree 
            #  run: sudo apt install -y tree

            #- name: List current folder after Build
            #  run: tree

            - name: List current folder after Build
              run: ls -la build/libs/

            - name: Login to Docker Hub
              uses: docker/login-action@v2
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build and push docker image
              uses: docker/build-push-action@v4
              with:
                context: .
                push: true
                tags: fillswim/mygifservice-githubactions:latest