name: GifService-Build-Wokflow

on:
    push:
      branches:
        - master

jobs:
    gifservice-build:
        runs-on: ubuntu-latest

        steps:

            - name: Git clone gifservice repository
              uses: actions/checkout@v1
            
            #- name: List current folder
            #  run: ls -la

            - name: Install Java
              uses: actions/setup-java@v3
              with:
                distribution: temurin
                java-version: 11
            
            - name: Check Java version
              run: java -version

            - name: Change wrapper permissions
              run: chmod +x ./gradlew
            
            - name: Init gradle wrapper
              run: gradle wrapper
            
            #- name: Build with Gradle wrapper
            #  run: ./gradlew build

            - name: Check Gradle version
              run: ./gradlew --version