name: GifService-Build-Wokflow

on:
    push:
      branches:
        - master

jobs:
    gifservice-build:
        runs-on: ubuntu-latest

        steps:

            - name: Git clone gifservice repository
              uses: actions/checkout@v1
            
            - name: List current folder
              run: ls -la
